/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TutorialsRouteImport } from './routes/tutorials'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RokuRouteImport } from './routes/roku'
import { Route as LogosRouteImport } from './routes/logos'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WatchChannelSlugRouteImport } from './routes/watch.$channelSlug'
import { Route as ChannelChannelSlugRouteImport } from './routes/channel.$channelSlug'
import { Route as ApiStreamProxyRouteImport } from './routes/api/stream-proxy'

const TutorialsRoute = TutorialsRouteImport.update({
  id: '/tutorials',
  path: '/tutorials',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RokuRoute = RokuRouteImport.update({
  id: '/roku',
  path: '/roku',
  getParentRoute: () => rootRouteImport,
} as any)
const LogosRoute = LogosRouteImport.update({
  id: '/logos',
  path: '/logos',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchChannelSlugRoute = WatchChannelSlugRouteImport.update({
  id: '/watch/$channelSlug',
  path: '/watch/$channelSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelChannelSlugRoute = ChannelChannelSlugRouteImport.update({
  id: '/channel/$channelSlug',
  path: '/channel/$channelSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStreamProxyRoute = ApiStreamProxyRouteImport.update({
  id: '/api/stream-proxy',
  path: '/api/stream-proxy',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/favorites': typeof FavoritesRoute
  '/logos': typeof LogosRoute
  '/roku': typeof RokuRoute
  '/settings': typeof SettingsRoute
  '/tutorials': typeof TutorialsRoute
  '/api/stream-proxy': typeof ApiStreamProxyRoute
  '/channel/$channelSlug': typeof ChannelChannelSlugRoute
  '/watch/$channelSlug': typeof WatchChannelSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/favorites': typeof FavoritesRoute
  '/logos': typeof LogosRoute
  '/roku': typeof RokuRoute
  '/settings': typeof SettingsRoute
  '/tutorials': typeof TutorialsRoute
  '/api/stream-proxy': typeof ApiStreamProxyRoute
  '/channel/$channelSlug': typeof ChannelChannelSlugRoute
  '/watch/$channelSlug': typeof WatchChannelSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/favorites': typeof FavoritesRoute
  '/logos': typeof LogosRoute
  '/roku': typeof RokuRoute
  '/settings': typeof SettingsRoute
  '/tutorials': typeof TutorialsRoute
  '/api/stream-proxy': typeof ApiStreamProxyRoute
  '/channel/$channelSlug': typeof ChannelChannelSlugRoute
  '/watch/$channelSlug': typeof WatchChannelSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/browse'
    | '/favorites'
    | '/logos'
    | '/roku'
    | '/settings'
    | '/tutorials'
    | '/api/stream-proxy'
    | '/channel/$channelSlug'
    | '/watch/$channelSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/browse'
    | '/favorites'
    | '/logos'
    | '/roku'
    | '/settings'
    | '/tutorials'
    | '/api/stream-proxy'
    | '/channel/$channelSlug'
    | '/watch/$channelSlug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/browse'
    | '/favorites'
    | '/logos'
    | '/roku'
    | '/settings'
    | '/tutorials'
    | '/api/stream-proxy'
    | '/channel/$channelSlug'
    | '/watch/$channelSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  BrowseRoute: typeof BrowseRoute
  FavoritesRoute: typeof FavoritesRoute
  LogosRoute: typeof LogosRoute
  RokuRoute: typeof RokuRoute
  SettingsRoute: typeof SettingsRoute
  TutorialsRoute: typeof TutorialsRoute
  ApiStreamProxyRoute: typeof ApiStreamProxyRoute
  ChannelChannelSlugRoute: typeof ChannelChannelSlugRoute
  WatchChannelSlugRoute: typeof WatchChannelSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tutorials': {
      id: '/tutorials'
      path: '/tutorials'
      fullPath: '/tutorials'
      preLoaderRoute: typeof TutorialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roku': {
      id: '/roku'
      path: '/roku'
      fullPath: '/roku'
      preLoaderRoute: typeof RokuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logos': {
      id: '/logos'
      path: '/logos'
      fullPath: '/logos'
      preLoaderRoute: typeof LogosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$channelSlug': {
      id: '/watch/$channelSlug'
      path: '/watch/$channelSlug'
      fullPath: '/watch/$channelSlug'
      preLoaderRoute: typeof WatchChannelSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channel/$channelSlug': {
      id: '/channel/$channelSlug'
      path: '/channel/$channelSlug'
      fullPath: '/channel/$channelSlug'
      preLoaderRoute: typeof ChannelChannelSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stream-proxy': {
      id: '/api/stream-proxy'
      path: '/api/stream-proxy'
      fullPath: '/api/stream-proxy'
      preLoaderRoute: typeof ApiStreamProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  BrowseRoute: BrowseRoute,
  FavoritesRoute: FavoritesRoute,
  LogosRoute: LogosRoute,
  RokuRoute: RokuRoute,
  SettingsRoute: SettingsRoute,
  TutorialsRoute: TutorialsRoute,
  ApiStreamProxyRoute: ApiStreamProxyRoute,
  ChannelChannelSlugRoute: ChannelChannelSlugRoute,
  WatchChannelSlugRoute: WatchChannelSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
